[log]
    level = "INFO"

[api]
    dashboard = true

[providers.docker]
    network = "traefik-shared"
    exposedByDefault = false

[entryPoints.websecure]
    address = ":443"

[certificatesResolvers.letsencrypt.acme]
    [certificatesResolvers.letsencrypt.acme.dnsChallenge]
        provider = "cloudflare"
        delayBeforeCheck = 0
